-- MySQL Script generated by MySQL Workbench
-- Sat Sep 19 13:28:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema me_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema me_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `me_db` DEFAULT CHARACTER SET utf8 ;
USE `me_db` ;

-- -----------------------------------------------------
-- Table `me_db`.`employee_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `me_db`.`employee_table` ;

CREATE TABLE IF NOT EXISTS `me_db`.`employee_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `gender` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NOT NULL,
  `job_titile` VARCHAR(45) NOT NULL,
  `signature` VARCHAR(45) NOT NULL,
  `registered_date` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_db`.`patient_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `me_db`.`patient_table` ;

CREATE TABLE IF NOT EXISTS `me_db`.`patient_table` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `patient_card_number` VARCHAR(45) NOT NULL,
  `patient_first_name` VARCHAR(45) NOT NULL,
  `patient_last_name` VARCHAR(45) NOT NULL,
  `patient_email` VARCHAR(45) NULL,
  `patient_phone` VARCHAR(45) NOT NULL,
  `patient_job_titile` VARCHAR(45) NULL,
  `patient_signature` VARCHAR(45) NULL,
  `patient_registered_date` VARCHAR(45) NOT NULL,
  `patient_age` INT NOT NULL,
  `patient_gender` VARCHAR(45) NOT NULL,
  `patient_status` VARCHAR(45) NOT NULL,
  `patient_wereda` INT NULL,
  `patient_kebele` INT NULL,
  `patient_address` VARCHAR(45) NOT NULL,
  `patient_session_status` VARCHAR(45) NOT NULL DEFAULT 'closed',
  `patient_session_open_at` DATETIME NOT NULL,
  `patient_session_closed_at` DATETIME NOT NULL,
  PRIMARY KEY (`patient_id`),
  UNIQUE INDEX `idusers_UNIQUE` (`patient_id` ASC),
  UNIQUE INDEX `patient_card_number_UNIQUE` (`patient_card_number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_db`.`patient_journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `me_db`.`patient_journal` ;

CREATE TABLE IF NOT EXISTS `me_db`.`patient_journal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_card_number` VARCHAR(45) NOT NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  `journal_long` LONGTEXT NOT NULL,
  `journal_summary` LONGTEXT NOT NULL,
  `journal_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idpatient_journal_UNIQUE` (`id` ASC),
  INDEX `fk_patient_journal_patient_table1_idx` (`patient_card_number` ASC),
  INDEX `fk_patient_journal_employee_table1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_patient_journal_patient_table1`
    FOREIGN KEY (`patient_card_number`)
    REFERENCES `me_db`.`patient_table` (`patient_card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_journal_employee_table1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `me_db`.`employee_table` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_db`.`lab_serology_coagulation_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `me_db`.`lab_serology_coagulation_table` ;

CREATE TABLE IF NOT EXISTS `me_db`.`lab_serology_coagulation_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_card_number` VARCHAR(45) NOT NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  `request_date` DATETIME NOT NULL,
  `completed_date` DATETIME NOT NULL,
  `results` JSON NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `employee_table_id` INT NOT NULL,
  `patient_table_patient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lab_serology_coagulation_table_employee_table1_idx` (`employee_id` ASC),
  INDEX `fk_lab_serology_coagulation_table_patient_table1_idx` (`patient_card_number` ASC),
  CONSTRAINT `fk_lab_serology_coagulation_table_employee_table1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `me_db`.`employee_table` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_serology_coagulation_table_patient_table1`
    FOREIGN KEY (`patient_card_number`)
    REFERENCES `me_db`.`patient_table` (`patient_card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_db`.`diagnos_vital_sign_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `me_db`.`diagnos_vital_sign_table` ;

CREATE TABLE IF NOT EXISTS `me_db`.`diagnos_vital_sign_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_card_number` VARCHAR(45) NOT NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  `blood_pressure` INT NOT NULL,
  `pluse_rate` INT NOT NULL,
  `respiration` INT NOT NULL,
  `temprature` INT NOT NULL,
  `oxygen_saturation` INT NOT NULL,
  `radom_blood_sugar` INT NOT NULL,
  `fasting_blood_sugar` INT NULL,
  `remarks` JSON NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_diagnos_vital_sign_table_patient_table1_idx` (`patient_card_number` ASC),
  INDEX `fk_diagnos_vital_sign_table_employee_table1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_diagnos_vital_sign_table_patient_table1`
    FOREIGN KEY (`patient_card_number`)
    REFERENCES `me_db`.`patient_table` (`patient_card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnos_vital_sign_table_employee_table1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `me_db`.`employee_table` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `me_db`.`admission_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `me_db`.`admission_table` ;

CREATE TABLE IF NOT EXISTS `me_db`.`admission_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient_card_number` VARCHAR(45) NOT NULL,
  `employee_id` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `bed_number` VARCHAR(45) NOT NULL,
  `examination_room` VARCHAR(45) NOT NULL,
  `refered_from` VARCHAR(45) NOT NULL,
  `allergies` VARCHAR(45) NOT NULL,
  `remarks` JSON NOT NULL,
  `admission_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_admission_table_patient_table1_idx` (`patient_card_number` ASC),
  INDEX `fk_admission_table_employee_table1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_admission_table_patient_table1`
    FOREIGN KEY (`patient_card_number`)
    REFERENCES `me_db`.`patient_table` (`patient_card_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admission_table_employee_table1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `me_db`.`employee_table` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
